import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./data/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#FFFFFF",
        "on-background": "#191c1e",
        surface: "#FFFFFF",
        "surface-dim": "#d9dadc",
        "surface-bright": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f6",
        "surface-container": "#edeef0",
        "surface-container-high": "#e7e8ea",
        "surface-container-highest": "#e1e2e4",
        "on-surface": "#191c1e",
        "on-surface-variant": "#444653",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f3",
        outline: "#757684",
        "outline-variant": "#c4c5d5",
        "surface-tint": "#005AA9",
        primary: "#005AA9",
        "on-primary": "#ffffff",
        "primary-container": "#0F2942",
        "on-primary-container": "#F1F5F9",
        "inverse-primary": "#b8c4ff",
        secondary: "#0F2942",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2e8f0",
        "on-secondary-container": "#005AA9",
        accent: "#D62828",
        "on-accent": "#ffffff",
        tertiary: "#6B7280",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#E5E7EB",
        "on-tertiary-container": "#1F2937",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dde1ff",
        "primary-fixed-dim": "#b8c4ff",
        "on-primary-fixed": "#001453",
        "on-primary-fixed-variant": "#173bab",
        "secondary-fixed": "#d5e3fd",
        "secondary-fixed-dim": "#b9c7e0",
        "on-secondary-fixed": "#0d1c2f",
        "on-secondary-fixed-variant": "#3a485c",
        "tertiary-fixed": "#E5E7EB",
        "tertiary-fixed-dim": "#D1D5DB",
        "on-tertiary-fixed": "#111827",
        "on-tertiary-fixed-variant": "#374151",
        "surface-variant": "#e1e2e4",
        "slate-text": "#0F172A",
        "border-subtle": "#E5E7EB",
        "success-industrial": "#059669",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "section-gap": "80px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        base: "8px",
      },
      fontFamily: {
        "technical-data": ["var(--font-jetbrains-mono)", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        "body-lg": ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-caps": ["var(--font-jetbrains-mono)", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        "headline-sm": ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-lg": ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-lg-mobile": ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-md": ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "technical-data": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [typography],
} satisfies Config;
